name: publish PDF

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download PDF
        uses: actions/download-artifact@v2
        with:
          name: lpantano-cv
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          publish_dir: lpantano-cv.pdf
