name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: lpantano-cv.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: lpantano-cv
          path: lpantano-cv.pdf
  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Download PDF
        uses: actions/download-artifact@v2
        with:
          name: lpantano-cv
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          publish_dir: lpantano-cv.pdf