name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: lpantano-cv.tex
      - name: my-cv
        uses: actions/upload-artifact@v2
        with:
          path: lpantano-cv.pdf